services:
    cards_data:
        class: AppBundle\Service\CardsData
        arguments: ["@doctrine", "@request_stack", "@router"]
    judge:
        class: AppBundle\Service\Judge
        arguments: ["@doctrine.orm.entity_manager"]
    decks:
        class: AppBundle\Service\Decks
        arguments: ["@doctrine.orm.entity_manager", "@judge", "@diff", "@logger"]
    decklists:
        class: AppBundle\Service\DecklistManager
        arguments: ["@doctrine.orm.entity_manager"]
    reviews:
        class: AppBundle\Service\Reviews
        arguments: ["@doctrine.orm.entity_manager"]
    texts:
        class: AppBundle\Service\Texts
        arguments: ["%kernel.root_dir%"]
    diff:
        class: AppBundle\Service\Diff
        arguments: ["@doctrine.orm.entity_manager"]
    activity_helper:
        class: AppBundle\Service\ActivityHelper
        arguments: ["@doctrine"]
    moderation_helper:
        class: AppBundle\Service\ModerationHelper
        arguments: ["@doctrine", "@mailer", "@twig", "@router", "@logger"]
    personalization_helper:
        class: AppBundle\Service\PersonalizationHelper
        arguments: ["@doctrine", "@activity_helper", "@security.authorization_checker"]
