AppBundle\Entity\Client:
    type: entity
    table: client
    oneToMany:
        claims:
            targetEntity: Claim
            mappedBy: client
            cascade: ["remove"]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            
