AppBundle\Entity\Prebuiltslot:
    type: entity
    table: prebuiltslot
    manyToOne:
        prebuilt:
            targetEntity: Prebuilt
            nullable: false
            inversedBy: slots
            joinColumn:
                name: prebuilt_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: smallint
    lifecycleCallbacks: {  }
